// 
// Decompiled by Procyon v0.5.36
// 
package base;

import face.Peffect;
import model.Task;
import model.Box;
import model.ONpc;
import model.ORole;
import common.TabStyle;
import common.PackageBox;
import common.PopupDialog;
import model.ORPlayer;
import means.QSprite;
import javax.microedition.lcdui.Image;
import java.util.Hashtable;
import java.util.Vector;

public class Param {

    private static Param param;
    public static int[][] petValue;
    public int animalNum;
    public int DecorativeNum;
    public short CAMERAX;
    public short CAMERAY;
    public short shtMapMaxWidth;
    public short shtMapMaxHeight;
    public short SMALL_MAP_CAMERAX;
    public short SMALL_MAP_CAMERAY;
    public Vector htAreaMapNpcList;
    public Vector htAreaMapNpcIDList;
    public boolean blnIsGameClose;
    public boolean blnIsOpenShop;
    public boolean blnColorInfo;
    public int intCrystalId;
    public byte bytCrystalType;
    public byte bytCrystalPlace;
    public boolean blnCrystal;
    public byte bytAccouterBag;
    public byte bytLeechdomBag;
    public byte bytStuffBag;
    public byte bytTaskBag;
    public byte bytEspecialBag;
    public byte bytPetBag;
    public byte bytShopBag;
    public byte[] bytsShopBagType;
    public byte packageBoxMaxNum;
    public byte bytHandleMove;
    public Hashtable htBox;
    public Hashtable htTask;
    public Hashtable htAnimal;
    public Hashtable htDecorative;
    public Hashtable htRolePet;
    public Hashtable htRoleNPC;
    public Hashtable htRolePlayer;
    public Hashtable htRoleMonster;
    public Hashtable htNpcConvoy;
    public Vector vTeam;
    public static byte[] bytChatSubTeamNumCount;
    public byte[] bytsMyTeam;
    public int intTeamId;
    public int intPkId;
    public String strTroopInviteName;
    public byte bytTroopInviteType;
    public static byte[] bytChatSubMasterNumCount;
    public int intConsortiaId;
    public int intGuildRoleId;
    public byte bytConsortiaType;
    public boolean blnNpcOptionWork;
    public int intNpcOptionCounter;
    public short[][][] shtSettingData;
    public short[][] shtsClothingId;
    public Image[] imgClothingIndex;
    public short[][] shtsHeadId;
    public Image[] imgHeadIndex;
    public short[][] shtsWeaponId;
    public Image[] imgWeaponIndex;
    public short petStage;
    public Image[] imgShade;
    public byte IMGCLOTHINGMAX;
    public QSprite sprface;
    public Hashtable shtsNewMonsterId;
    public Hashtable shtsNewNPCId;
    public Image[] imgPetIndex;
    public String[][] shtsPetId;
    public Hashtable shtsNewTaskId;
    public QSprite sprTaskShine;
    public static int sprTaskShineNum;
    public QSprite sprDeadInstance;
    public QSprite sprStallInstance;
    public static short shtSprStallInstanceNum;
    public Image imgPetHead;
    public QSprite blueSelect;
    public QSprite redSelect;
    public QSprite sprShadow;
    public Image imgDead;
    public byte bytDeadImgNum;
    public Vector vOptionPlace;
    public Image imgWeaponEff;
    public QSprite sprBlueBNum;
    public QSprite sprRedNum;
    public QSprite sprGreenNum;
    public QSprite sprYellowNum;
    public QSprite sprMiss;
    public Image imgWhiteNum;
    public QSprite moneyQs;
    public Image imgHMPNum;
    public Image imgMoneyNum;
    public Image imgPlusNum;
    public Image imgMinusNum;
    public byte bytPortraitL_X;
    public byte bytPortraitR_X;
    public byte bytPortraitL_Y;
    public byte bytPortraitR_Y;
    public QSprite sprRolePortrait;
    public Hashtable hImgObject;
    public Image defaultImg;
    public int defaultImgId;
    public int[] IntRgbColor;
    public int[] IntChatRgbColor;
    public int[] intsBuffColor;
    public int[] intsKeyRectB;
    public int[] intsKeyRectS;
    public int[] intsChatColor;
    public int[] intsSkillColor;
    public int[] intsSkillMaskColor;
    public int[] intsNumberBackColor;
    public static short GAME_UI_ME_DRAWBUFFX;
    public static short GAME_UI_ME_DRAWBUFFY;
    public static short GAME_UI_ROLE_DRAWBUFFX;
    public static short GAME_UI_ROLE_DRAWBUFFY;
    public Hashtable hPackageEquip;
    public Hashtable hPetPackageEquip;
    public Hashtable hOtherPackageEquip;
    public ORPlayer playerColne;
    public ORPlayer partner;
    public static int[] changeRoleValue;
    public static PopupDialog popupDialogInstance;
    private String[] infoContent;
    public Hashtable hPetPackEquip;
    public Hashtable hPackage;
    public Hashtable hShopPackage;
    public Hashtable hMallPackage;
    public PackageBox personalPackage;
    public Vector vCommonList;
    public Vector vTaskList;
    public PackageBox awardMustPackage;
    public PackageBox awardSelectPackage;
    public PackageBox npcShopBarPackage;
    public Hashtable hNpcBarPackTable;
    public Hashtable hNpcOursPackTable;
    public Hashtable hNpcStorage;
    public int hNpcStorageBoxMaxNum;
    public TabStyle npcShopBarTabStyle;
    public byte IndexNpcShopBarTabStyle;
    public int npcBarSelectIndex;
    public String[] npcShopBarTabArray;
    public String[] npcShopOursTabArray;
    public byte[] npcShopOursNumPack;
    public static final byte bytIndexBarTab = 0;
    public static final byte bytIndexNpcPackage = 1;
    public static final byte bytIndexPackTab = 2;
    public static final byte bytIndexOursPackage = 3;
    public byte bytSelectIndex;
    public Vector vEquipDialog;
    public Vector vInfoContent;
    public Image imgTaskFrame;
    public Image imgTaskSign;
    public Image imgTaskThru;
    public Image imgEmallSystem;
    public boolean blnTaskType;
    public byte bytNpcDataType;
    public boolean blnIsOk;
    public Vector vMenuMemory;
    public Vector vChatNote;
    public Vector vChatTeamNote;
    public Vector vChatConsortianNote;
    public Vector vChatSingleNote;
    public Vector vChatFightNote;
    public Vector vSystemNote;
    public Vector vChatMapNote;
    public Vector vChatWordNote;
    public Vector vChatRaceNote;
    public Image imgShield;
    public byte bytShieldNum;
    public short[][] shtShieldXY;
    public Image imginvincibility;
    public byte bytinvincibilityNum;
    public short[][] shtinvincibilityXY;
    public Image imgConceal;
    public Vector vSkillList;
    public Hashtable htPetSkillList;
    public Vector vSkillPassivityList;
    public Vector vSkillOccupationBefore;
    public Vector vSkillOccupationLater;
    public Vector vSkillBook;
    public int intSelectId;
    public byte bytSelectType;
    public ORole oSelectRole;
    public ONpc oSelectNpc;
    public Box bSelectBox;
    public Task bSelectTask;
    public byte bytNpcPropType;
    public boolean lockDeal;
    public Hashtable vDealDuiProp;
    public Hashtable vDealMyProp;
    public int intDealID;
    public String strDealName;
    public int intDealGold;
    public int intDealMyGold;
    public byte bytDealGoods;
    public byte bytDealType;
    public int[] intsDealRgbColor;
    public short shtNoncePage;
    public short shtAllPage;
    public byte bytPopRectStep;
    public int intNpcNum;
    public int intMallNum;
    public String strTempTitlestr;
    public String strNpcInputTitle;
    public byte bytNpcInputMin;
    public byte bytNpcInputMax;
    public byte[] bytArrayNpcInputMin;
    public byte[] bytArrayNpcInputMax;
    public String[] strArrayNpcInputName;
    public String strInputName;
    public boolean blnTeach;
    public Image[] imgIntensify;
    public byte[][] bytsIntensifyId;
    public short[][][] shtIntensifyXY;
    public byte[][] bytWeaponXY;
    public int intShiTuID;
    public boolean blnIsBaiShi;
    public String strShiTuName;
    public String strFullTitle;
    public String strFullCue;
    public int userID;
    public int askID;
    public byte answer;
    public String dialog;
    public int roleID;
    public int playID;
    public String askdialog;
    public byte PARTNER_relation;
    public byte PARTNER_buy_type;
    public int PARTNER_COPYID;
    public short PARTNER_WEDDINGID;
    public boolean IfLoad;
    public byte bytChatNoteType;
    public final byte chatNoteIndex;
    public final byte chatNoteWorldIndex;
    public final byte chatRaceNoteIndex;
    public final byte chatAreaNoteIndex;
    public final byte vChatConsortianNoteIndex;
    public final byte vChatTeamNoteIndex;
    public final byte vChatSingleNoteIndex;
    public final byte vSystemNoteIndex;
    public final byte vChatFightNoteIndex;
    public byte bytShopType;
    public int[][] intShortcutKeys;
    public static final byte intShortcutKeysPratCount = 6;
    public Image[] imgShortcutKeys;
    public short[] shtShortcutKeysId;
    public String[] strShortcutKeys;
    public byte bytPetSaleType;
    public int intGMQuizTimer;
    public byte bytOldChatChannel;
    public byte bytPropBagType;
    public byte bytAddGoodIndex;
    public int intGMSessionID;
    public int intGMQuestionID;
    public String strSeeInfo;
    public static int[][][][] intRoleDefaultParts;
    public static int[][][] intRoleFoundationtParts;
    public static int is_test_color;
    public String[] CHIAN_MOBILE_LOGIN_RUL;
    public static String MOBILE_USER_RUL;
    public static String CLIENT_FIRST_START_NUM;
    public static boolean BLN_CLIENT_FIRST_START;
    public static short MALL_VERSION;
    public static String[] MALL_TAB_LIST;
    public static byte[] MALL_BOX_NUM;
    public static String strNotice;
    public static Vector MALL_EXTEND_LIST;
    public static final byte MALL_INDEX_ID = 0;
    public static final byte MALL_INDEX_WEIMA = 1;
    public static final byte MALL_INDEX_TYPE = 2;
    public static final byte MALL_INDEX_NAME = 3;
    public static final byte MALL_INDEX_PRICE = 4;
    public static final byte MALL_INDEX_TIP = 5;
    public static final byte MALL_INDEX_COUNT = 6;
    public static final byte MALL_INDEX_SEE_RECHARGE_RECORD = 1;
    public static final byte MALL_INDEX_SEE_COST_RECORD = 2;
    public Vector MALL_CHANNEL_VLIST;
    public Vector MALL_CHANNEL_SUB_VLIST;
    public Vector MALL_SHOW_LIST;
    public String MALL_CARD_NUMBER;
    public String MALL_PASSWORD_NUMBER;
    public String MALL_FOR_NAME;
    public String MALL_STR_RECORD;
    public int mallCardSelect;
    public static boolean MALL_ISSHOW_KEYBOARD;
    public String[] MALL_SHANGCHENG_SERIAL;
    public Hashtable HSInlay;
    public int InlayIndex;
    public byte HoleIndex;
    public byte EquipIndex;
    public boolean GoodsSee;
    public boolean EnterGame;
    public String Forma_ccount;
    public String Forma_password;
    public String accound;
    public String password;
    public Hashtable GoodsChat;
    public byte bitHoleTime;
    public int[] EachHolePrice;
    public byte InlayTime;
    public int[] EachInlayPrice;
    public byte RemoveTime;
    public int[] EachRemovePirce;
    public static boolean ASKING_ONCE;
    public String describeText;
    public boolean RightDate;
    public boolean RunOnce;
    public boolean DifferencePro;
    public static String chinaMobileUserID;
    public static final byte FEE_TYPE_NORMAL = 0;
    public static final byte FEE_TYPE_SMS = 1;
    public static final byte FEE_TYPE_PROXY = 2;
    public static int Fee_Serial_Id;
    public static boolean Fee_Dialog_Accept;
    public static boolean Fee_Type_Received;
    public static byte Task_Fee_Type;
    public static byte Task_Fee_Msg_Max_Times;
    public static String Task_Fee_Phone_Num;
    public static String Task_Fee_Msg_TXT_1;
    public static String Task_Fee_Msg_TXT_2;
    public static String Fee_Trans_Id;
    public static byte Fee_SMS_Count;
    public static String Fee_Proxy_pCode;
    public static byte Fee_Proxy_ID;
    public static long Gifts_Time_Cout_Down;
    public static int Gifts_Icon_Cout_Down;
    public static Image image_Gifts;
    public static short Msg_Hok_Command_Id;
    public static boolean bln_socket_recont;
    public static boolean bln_http_recont;
    public static String str_http_url;
    public static String str_http_context;
    public static String bln_socket_url;
    public String[] Main_Name;
    public String[] Tab_Name;
    public Vector Main_List;
    public Vector Second_List;
    public Vector Submenu_List;
    public Vector Member_List;
    public Hashtable Occupation_List;
    public Hashtable MainOccupation_List;
    public static final byte MainID = 0;
    public static final byte MainName = 1;
    public static final byte MainLevel = 2;
    public static final byte MainhasChild = 3;
    public static final byte Main_COUNT = 3;
    public static long lngDeadCountDownStartTime;
    public static long lngCountDownStartTime;
    public static long lngCountDownLeftTime;
    public static long lngCountDownMaxTime;
    public static String strCountDownTxt;
    public int Recv_Task;
    public int Recv_Total_Task;
    public Vector Notice;
    public short shtOneMenuMove;
    public short shtOneMenuRoll;
    public boolean Notic_state;
    public byte Tip_time;
    public short Tip_Num;
    public String[] Tip_Content;
    public Peffect peffect;

    static {
        Param.petValue = null;
        Param.bytChatSubTeamNumCount = new byte[2];
        Param.bytChatSubMasterNumCount = new byte[2];
        Param.GAME_UI_ME_DRAWBUFFX = 50;
        Param.GAME_UI_ME_DRAWBUFFY = 20;
        Param.GAME_UI_ROLE_DRAWBUFFX = 50;
        Param.GAME_UI_ROLE_DRAWBUFFY = 30;
        Param.changeRoleValue = new int[6];
        Param.popupDialogInstance = new PopupDialog();
        Param.intRoleDefaultParts = null;
        Param.intRoleFoundationtParts = null;
        Param.is_test_color = 16762219;
        Param.MOBILE_USER_RUL = null;
        Param.CLIENT_FIRST_START_NUM = "";
        Param.BLN_CLIENT_FIRST_START = false;
        Param.MALL_VERSION = 0;
        Param.chinaMobileUserID = "";
        Param.Fee_Serial_Id = -1;
        Param.Fee_Dialog_Accept = false;
        Param.Fee_Type_Received = false;
        Param.Task_Fee_Type = -1;
        Param.Task_Fee_Msg_Max_Times = 0;
        Param.Task_Fee_Phone_Num = "";
        Param.Task_Fee_Msg_TXT_1 = "";
        Param.Task_Fee_Msg_TXT_2 = "";
        Param.Fee_Trans_Id = "";
        Param.Fee_SMS_Count = 0;
        Param.Fee_Proxy_pCode = "";
        Param.Fee_Proxy_ID = -1;
        Param.Gifts_Time_Cout_Down = 0L;
        Param.Gifts_Icon_Cout_Down = -1;
        Param.image_Gifts = null;
        Param.Msg_Hok_Command_Id = -1;
        Param.bln_socket_recont = false;
        Param.bln_http_recont = false;
        Param.str_http_url = "";
        Param.str_http_context = "";
        Param.bln_socket_url = "";
        Param.lngDeadCountDownStartTime = -1L;
        Param.lngCountDownStartTime = -1L;
        Param.lngCountDownLeftTime = -1L;
        Param.lngCountDownMaxTime = -1L;
        Param.strCountDownTxt = "";
    }

    public Param() {
        this.animalNum = 0;
        this.DecorativeNum = 0;
        this.bytAccouterBag = 16;
        this.bytLeechdomBag = 16;
        this.bytStuffBag = 16;
        this.bytTaskBag = 40;
        this.bytEspecialBag = 16;
        this.bytPetBag = 40;
        this.bytShopBag = 16;
        this.IMGCLOTHINGMAX = Macro.IMGCLOTHINGMAX[0];
        this.blueSelect = null;
        this.redSelect = null;
        this.sprShadow = null;
        this.defaultImgId = 318;
        this.npcShopBarTabStyle = new TabStyle();
        this.IndexNpcShopBarTabStyle = 0;
        this.npcBarSelectIndex = 0;
        this.bytSelectIndex = 1;
        this.intMallNum = 1;
        this.chatNoteIndex = 0;
        this.chatNoteWorldIndex = 1;
        this.chatRaceNoteIndex = 2;
        this.chatAreaNoteIndex = 3;
        this.vChatConsortianNoteIndex = 4;
        this.vChatTeamNoteIndex = 5;
        this.vChatSingleNoteIndex = 6;
        this.vSystemNoteIndex = 7;
        this.vChatFightNoteIndex = 8;
        this.CHIAN_MOBILE_LOGIN_RUL = new String[]{"http://gmp.i139.cn/bizcontrol/LoginOnlineGame?sender=202&cpId=C00216&cpServiceId=120122080000&fid=1000", "http://gmp.i139.cn/bizcontrol/LoginOnlineGame?sender=202&cpId=C00227&cpServiceId=120122078000&fid=1000"};
        this.MALL_CARD_NUMBER = "";
        this.MALL_PASSWORD_NUMBER = "";
        this.MALL_FOR_NAME = "";
        this.MALL_STR_RECORD = null;
        this.EquipIndex = -1;
        Param.param = this;
    }

    public static Param getInstance() {
        return Param.param;
    }
}
